version: '3'

services:
  react-app:
    build: .
    image: react-app
    ports:
      - '4000:4000'
    volumes:
      - .:/home/node/react-app:rw
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge