version: '3'

services:
  react-app:
    build: .
    image: react-app
    ports:
      - '4000:4000'
    volumes:
      - .:/home/node/react-app:rw
    networks:
      - express-install-backend_node-network

volumes:
  dbdata:

networks:
  express-install-backend_node-network:
      external: true